CREATE DATABASE FLIGHT_RESERVATION;
USE FLIGHT_RESERVATION;

CREATE TABLE USER
(
ID INT NOT NULL auto_increment,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
EMAIL VARCHAR(30),
PASSWORD VARCHAR(260),
PRIMARY KEY(ID),
UNIQUE KEY (EMAIL)
);

select * from  USER;

CREATE TABLE FLIGHT
(
ID INT NOT NULL auto_increment,
FLIGHT_NUMBER VARCHAR(30) NOT NULL,
OPERATING_AIRLINES VARCHAR(30) NOT NULL,
DEPARTURE_CITY VARCHAR(30)  NOT NULL,
  ARRIVAL_CITY VARCHAR(30)  NOT NULL,
  DATE_OF_DEPARTURE DATE  NOT NULL,
  DATE_OF_ARRIVAL DATE  NOT NULL,
  ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
PRIMARY KEY(ID)
);
select * from  FLIGHT;

CREATE TABLE PASSENGER
(
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(200),
  LAST_NAME VARCHAR(200),
  MIDDLE_NAME VARCHAR(200),
  EMAIL VARCHAR(60),
  PHONE VARCHAR(10),
  PRIMARY KEY (ID)
);
select * from  PASSENGER;

CREATE TABLE RESERVATION
(
  ID INT NOT NULL AUTO_INCREMENT,
  CHECKED_IN TINYINT(1),
  NUMBER_OF_BAGS INT,
  PASSENGER_ID INT,
  FLIGHT_ID INT,
  CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE,
  FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID)
);
select * from  RESERVATION;

SHOW TABLES;
 